name: deploy-infra

on:
  push:
    paths:
      - 'infra/**' 
  workflow_dispatch:

env:
  RESOURCE_GROUP_DEV: aguadamillas_students_1
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: beaamoo
  containerRegistryName: 'beaamooacr'  # Replace with actual ACR name
  keyVaultName: 'beaamoo-kv'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Print current directory
        run: |
          pwd
          ls -R
      - name: Run Bicep Linter for key-vault.bicep
        run: |
          pwd
          cd infra
          ls -R
          az bicep build --file key-vault.bicep
      - name: Run Bicep Linter for main.bicep
        run: |
          pwd
          cd infra
          ls -R
          az bicep build --file main.bicep

  deploy-acr-and-keyvault:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Key Vault and ACR
        uses: azure/arm-deploy@v1.0.9
        with:
          scope: resourcegroup
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./infra/key-vault-and-acr.bicep
          parameters: ./infra/parameters/key-vault-and-acr.json
          deploymentName: '${{env.USER_ALIAS}}-kv-acr'

  setup-acr-credentials:
    runs-on: ubuntu-latest
    needs: deploy-acr-and-keyvault
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Get ACR credentials'
        run: |
          ACR_CREDENTIALS=$(az acr credential show --name ${{ env.containerRegistryName }} --query "[username,passwords[0].value]" --output tsv)
          ACR_USERNAME=$(echo $ACR_CREDENTIALS | cut -f1)
          ACR_PASSWORD=$(echo $ACR_CREDENTIALS | cut -f2)
          echo "ACR_USERNAME=$ACR_USERNAME" >> $GITHUB_ENV
          echo "ACR_PASSWORD=$ACR_PASSWORD" >> $GITHUB_ENV
      - name: 'Store ACR credentials in Key Vault'
        run: |
          az keyvault secret set --vault-name ${{ env.keyVaultName }} --name "acr-username" --value $ACR_USERNAME
          az keyvault secret set --vault-name ${{ env.keyVaultName }} --name "acr-password1" --value $ACR_PASSWORD

  deploy-other-resources:
    runs-on: ubuntu-latest
    needs: setup-acr-credentials
    steps:
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Remaining Resources
        uses: azure/arm-deploy@v1.0.9
        with:
          scope: resourcegroup
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./infra/main.bicep  # Adjusted the path
          parameters: ./infra/parameters/main.json  # Adjusted the path
          deploymentName: '${{env.USER_ALIAS}}-main'
